<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="5" tests="2" time="119.414">
 <testsuite name="ENDEVOUR CYPRESS AUTOMATION : vrifying the page content of child window contains the text Why Cypress" timestamp="2019-12-11T17:06:45" hostname="localhost" time="73.519" errors="0" tests="1" skipped="0" disabled="0" failures="2">
  <testcase classname="ENDEVOUR CYPRESS AUTOMATION : vrifying the page content of child window contains the text Why Cypress" name="verify that Cypress web site child window page content has the text WHY CYPRESS  : WhyCypress_FirstDataSets" time="73.132">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)]]>
   </failure>
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="ENDEVOUR CYPRESS SITE TEST AUTOMATION: verifying  the landing page(current URL) has the text cypress" timestamp="2019-12-11T17:07:58" hostname="localhost" time="45.895" errors="0" tests="1" skipped="0" disabled="0" failures="3">
  <testcase classname="ENDEVOUR CYPRESS SITE TEST AUTOMATION: verifying  the landing page(current URL) has the text cypress" name="the cypress landing page url contain the text cypress : urlCurrent_Content_FirstDataSets" time="45.809">
   <failure type="exception" message="Error: ENOENT: no such file or directory, open &apos;C:\Users\Owner\Desktop\EndevourCucumberDemo2\screenshots\chrome-ENDEVOUR CYPRESS AUTOMATION : vrifying the page content of child window contains the text Why Cypress verify that Cypress web site child window page content has the text WHY CYPRESS  : WhyCypress_FirstDataSets.png&apos;"><![CDATA[Error: ENOENT: no such file or directory, open 'C:\Users\Owner\Desktop\EndevourCucumberDemo2\screenshots\chrome-ENDEVOUR CYPRESS AUTOMATION : vrifying the page content of child window contains the text Why Cypress verify that Cypress web site child window page content has the text WHY CYPRESS  : WhyCypress_FirstDataSets.png']]>
   </failure>
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)]]>
   </failure>
   <failure type="exception" message="Failed: Wait timed out after 12139ms"><![CDATA[TimeoutError: Wait timed out after 12139ms
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2201:17
    at ManagedPromise.invokeCallback_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: <anonymous wait>
    at scheduleWait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2188:20)
    at ControlFlow.wait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2517:12)
    at Driver.wait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
    at run (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
    at GoogleSearchListPage.selectSearchText (C:\Users\Owner\Desktop\EndevourCucumberDemo2\pages\GoogleSearchListPage.js:8:21)
    at UserContext.<anonymous> (C:\Users\Owner\Desktop\EndevourCucumberDemo2\specDefs\urlContentVerification_spec.js:39:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Run it("the cypress landing page url contain the text cypress : urlCurrent_Content_FirstDataSets") in control flow
    at UserContext.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at handleError (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4244:11)
    at process.onerror (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2371:17)
    at process.emit (events.js:198:13)
    at process.emit (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:439:21)
From asynchronous test: 
Error
    at C:\Users\Owner\Desktop\EndevourCucumberDemo2\specDefs\urlContentVerification_spec.js:22:5
    at C:\Users\Owner\Desktop\EndevourCucumberDemo2\node_modules\jasmine-data-provider\src\index.js:37:22
    at Array.forEach (<anonymous>)
    at C:\Users\Owner\Desktop\EndevourCucumberDemo2\node_modules\jasmine-data-provider\src\index.js:30:24
    at Suite.<anonymous> (C:\Users\Owner\Desktop\EndevourCucumberDemo2\specDefs\urlContentVerification_spec.js:21:3)
    at addSpecsToSuite (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (C:\Users\Owner\Desktop\EndevourCucumberDemo2\specDefs\urlContentVerification_spec.js:12:1)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>